services:
  server:
    image: planit-server-dev
    container_name: planit-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env.local
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    container_name: planit-db-dev
    ports:
      - '5432:5432'
    env_file:
      - ./server/.env.local
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  redis:
    image: redis:alpine
    container_name: planit-store

  client:
    image: planit-frontend-dev
    container_name: planit-frontend-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true
