name: Build and publish images and deploy to server

on:
  push:
    branches: [master]
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Frontend image
        run: |
          cd client
          docker build -f Dockerfile.prod -t ghcr.io/leeviko/planit-frontend .
          docker push ghcr.io/leeviko/planit-frontend
      - name: Backend image
        run: |
          cd server
          docker compose build
          docker compose push
  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/www/planit
            sh init.sh
