name: Build and publish images and deploy to server

on:
  push:
    branches: [master]
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Frontend image
        run: |
          cd client
          docker build -f Dockerfile.prod -t ghcr.io/leeviko/planit-frontend .
          docker push ghcr.io/leeviko/planit-frontend
      - name: Backend image
        run: |
          cd server
          docker compose build
          docker compose push
